### ISSUE TITLE
Type referenced from a stored property in a '@​frozen' struct must be '@​usableFromInline' or public

### ISSUE THREAD

**Issue by grgar** [xavierLowmiller/AppStorage#7]
I'm getting the following error on this line in Xcode 12.5 beta 3 (12E5244e) that I wasn't getting in Xcode 12.4.

https://github.com/xavierLowmiller/AppStorage/blob/db62f9cd3aec28e901900b9ea71ec38c0665d9f3/Sources/AppStorage/AppStorage.swift#L7

> Type referenced from a stored property in a '@​frozen' struct must be '@​usableFromInline' or public

<img width="1374" alt="Screenshot 2021-03-16 at 8 44 48 am" src="https://user-images.githubusercontent.com/191085/111280741-15f91980-8634-11eb-8894-ebec2d1d99bb.png">

I apparently fixed it locally by removing `@​frozen` on line 5 but not sure if the other option is a better solution.

**Comment by xavierLowmiller** [comment]
Thanks for bringing this to my attention! I'll look into providing a fix soon.

**Comment by xavierLowmiller** [comment]
@grgarside Can you check with the newly released version `1.0.4`?

**Comment by grgar** [comment]
All good now, thank you!

Thanks for this fantastic project too by the way :)

**Comment by xavierLowmiller** [comment]
Thanks!

I'm glad I could help :v:
